directories:
  persist_vector_directory: data/vector_db
  data_product_directory: data/data_csv/product_csv.csv
  database_product_directory: data/database/product.db

llm_config:
  rag_model: Llama3-70b-8192
  temperature: 0.0
  max_token: 1024

retriever_config:
  similarity_score: 0.5
  embedding_model: BAAI/bge-base-en-v1.5
  vector_embed_size: 768
  top_k: 3
  score_thres: 0.7

chunk_config:
  chunk_size: 1248
  chunk_overlap: 200
